dbt:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: ap-southeast-2
      s3_data_dir: 's3://tiki-data-bucket/warehouse'
      s3_staging_dir: s3://stg-data--bucket/athena-staging/
      schema: tiki_dwh
      threads: 4
      type: athena
  target: dev
